# Generated by Django 5.2.1 on 2025-05-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
