# Generated by Django 5.2.1 on 2025-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useractionlog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='static_user',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
